
services:
    db:
        container_name: postgres
        image: postgres:latest
        env_file: ./.env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - '${DB_PORT_LOCAL}:${DB_PORT_DOCKER}'
        networks:
            - app-network
        restart: unless-stopped

    smtp4dev:
        image: rnwood/smtp4dev:v3
        env_file: ./.env
        restart: always
        ports:
            - '${SMTP_WEB_PORT_LOCAL}:${SMTP_WEB_PORT_DOCKER}'
            - '${SMTP_SERVER_PORT_LOCAL}:${SMTP_SERVER_PORT_DOCKER}'
            - '${IMAP_PORT_LOCAL}:${IMAP_PORT_DOCKER}'
        volumes:
            - smtp4dev-data:/smtp4dev
        depends_on:
            - db
        environment:
            - ServerOptions__HostName=${SMTP_HOST}
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${SERVER_PORT_LOCAL}:${SERVER_PORT_DOCKER}'
        env_file: ./.env
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT_DOCKER}/${DB_NAME}
            SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
            SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
            SPRING_MAIL_HOST: ${SMTP_HOST}
            SPRING_MAIL_PORT: ${SMTP_SERVER_PORT_DOCKER}
        networks:
            - app-network
        depends_on:
            - db
            - smtp4dev
        restart: always

networks:
    app-network:
        driver: bridge

volumes:
    db:
    smtp4dev-data:
